# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'contracts',
            },
        ),
        migrations.CreateModel(
            name='FProficiency',
            fields=[
                ('language', models.CharField(db_column='Language', max_length=20, primary_key=True, serialize=False)),
                ('star_rating', models.DecimalField(blank=True, db_column='Star_rating', decimal_places=2, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'f_proficiency',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(db_column='Message', max_length=1000)),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='ParticipateIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'participate_in',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('class_field', models.CharField(blank=True, db_column='Class', max_length=1, null=True)),
                ('file', models.FileField(db_column='Filepath', upload_to='')),
            ],
            options={
                'db_table': 'portfolio',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('req_id', models.IntegerField(db_column='Req_id', primary_key=True, serialize=False)),
                ('fund', models.IntegerField(blank=True, db_column='Fund', null=True)),
                ('start_date', models.DateField(blank=True, db_column='Start_date', null=True)),
                ('end_date', models.DateField(blank=True, db_column='End_date', null=True)),
                ('min_exp', models.IntegerField(blank=True, db_column='Min_exp', default=0, null=True)),
                ('min_fre', models.IntegerField(blank=True, db_column='Min_fre', default=1, null=True)),
                ('max_fre', models.IntegerField(blank=True, db_column='Max_fre', default=1, null=True)),
                ('team_only', models.IntegerField(blank=True, db_column='Team_only', default=False, null=True)),
                ('state', models.IntegerField(db_column='State', default=0)),
                ('frating', models.DecimalField(blank=True, db_column='Frating', decimal_places=2, default=None, max_digits=3, null=True)),
                ('crating', models.DecimalField(blank=True, db_column='Crating', decimal_places=2, default=None, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'request',
            },
        ),
        migrations.CreateModel(
            name='RequestAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('askdate', models.DateField(blank=True, db_column='Askdate', null=True)),
                ('asktime', models.TimeField(blank=True, db_column='Asktime', null=True)),
                ('rid', models.ForeignKey(db_column='Rid', on_delete=django.db.models.deletion.CASCADE, to='headhunt.Request')),
            ],
            options={
                'db_table': 'request_ask',
            },
        ),
        migrations.CreateModel(
            name='RequestDoc',
            fields=[
                ('doc_id', models.IntegerField(db_column='Doc_id', primary_key=True, serialize=False)),
                ('doc', models.FileField(db_column='Docpath', upload_to='')),
                ('req', models.ForeignKey(db_column='Req_id', on_delete=django.db.models.deletion.CASCADE, to='headhunt.Request')),
            ],
            options={
                'db_table': 'request_doc',
            },
        ),
        migrations.CreateModel(
            name='RequestTeamAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('askdate', models.DateField(blank=True, db_column='Askdate', null=True)),
                ('asktime', models.TimeField(blank=True, db_column='Asktime', null=True)),
                ('rid', models.ForeignKey(db_column='Rid', on_delete=django.db.models.deletion.CASCADE, to='headhunt.Request')),
            ],
            options={
                'db_table': 'request_team_ask',
            },
        ),
        migrations.CreateModel(
            name='ResultDoc',
            fields=[
                ('doc_id', models.IntegerField(db_column='Doc_id', primary_key=True, serialize=False)),
                ('doc', models.FileField(db_column='Docpath', upload_to='')),
                ('req', models.ForeignKey(db_column='Req_id', on_delete=django.db.models.deletion.CASCADE, to='headhunt.Request')),
            ],
            options={
                'db_table': 'result_doc',
            },
        ),
        migrations.CreateModel(
            name='RProficiency',
            fields=[
                ('language', models.CharField(db_column='Language', max_length=20, primary_key=True, serialize=False)),
                ('star_rating', models.DecimalField(blank=True, db_column='Star_rating', decimal_places=2, default=0.0, max_digits=3, null=True)),
                ('req', models.ForeignKey(db_column='Req_id', on_delete=django.db.models.deletion.CASCADE, to='headhunt.Request')),
            ],
            options={
                'db_table': 'r_proficiency',
            },
        ),
        migrations.CreateModel(
            name='TContracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.ForeignKey(db_column='Rid', on_delete=django.db.models.deletion.CASCADE, to='headhunt.Request')),
            ],
            options={
                'db_table': 't_contracts',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('tname', models.CharField(db_column='Tname', max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.CharField(db_column='Id', max_length=14, primary_key=True, serialize=False)),
                ('pw', models.CharField(db_column='Pw', max_length=20)),
                ('is_admin', models.IntegerField(blank=True, db_column='Is_admin', default=False, null=True)),
                ('uname', models.CharField(db_column='UName', max_length=20)),
                ('phone_num', models.CharField(blank=True, db_column='Phone_num', max_length=11, null=True)),
                ('rating', models.DecimalField(blank=True, db_column='Rating', decimal_places=2, default=None, max_digits=3, null=True)),
                ('user_type', models.CharField(db_column='User_type', max_length=1)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.ForeignKey(db_column='Id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='headhunt.Users')),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Freelancers',
            fields=[
                ('id', models.ForeignKey(db_column='Id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='headhunt.Users')),
                ('age', models.IntegerField(blank=True, db_column='Age', null=True)),
                ('exp', models.IntegerField(blank=True, db_column='Exp', null=True)),
                ('major', models.CharField(blank=True, db_column='Major', max_length=30, null=True)),
            ],
            options={
                'db_table': 'freelancers',
            },
        ),
        migrations.AddField(
            model_name='tcontracts',
            name='tname',
            field=models.ForeignKey(db_column='Tname', on_delete=django.db.models.deletion.CASCADE, to='headhunt.Teams'),
        ),
        migrations.AddField(
            model_name='requestteamask',
            name='tname',
            field=models.ForeignKey(db_column='Tname', on_delete=django.db.models.deletion.CASCADE, to='headhunt.Teams'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='req',
            field=models.ForeignKey(blank=True, db_column='Req_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='headhunt.Request'),
        ),
        migrations.AddField(
            model_name='participatein',
            name='tname',
            field=models.ForeignKey(db_column='Tname', on_delete=django.db.models.deletion.CASCADE, to='headhunt.Teams'),
        ),
        migrations.AddField(
            model_name='message',
            name='rid',
            field=models.ForeignKey(db_column='Rid', on_delete=django.db.models.deletion.CASCADE, to='headhunt.Request'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='rid',
            field=models.ForeignKey(db_column='Rid', on_delete=django.db.models.deletion.CASCADE, to='headhunt.Request'),
        ),
        migrations.AddField(
            model_name='teams',
            name='leader',
            field=models.ForeignKey(blank=True, db_column='Id', null=True, on_delete=django.db.models.deletion.CASCADE, to='headhunt.Freelancers'),
        ),
        migrations.AddField(
            model_name='tcontracts',
            name='cid',
            field=models.ForeignKey(db_column='Cid', on_delete=django.db.models.deletion.CASCADE, to='headhunt.Clients'),
        ),
        migrations.AlterUniqueTogether(
            name='requestteamask',
            unique_together=set([('rid', 'tname')]),
        ),
        migrations.AddField(
            model_name='requestask',
            name='fid',
            field=models.ForeignKey(db_column='Fid', on_delete=django.db.models.deletion.CASCADE, to='headhunt.Freelancers'),
        ),
        migrations.AddField(
            model_name='request',
            name='cid',
            field=models.ForeignKey(blank=True, db_column='Cid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='headhunt.Clients'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='fid',
            field=models.ForeignKey(blank=True, db_column='Fid', null=True, on_delete=django.db.models.deletion.CASCADE, to='headhunt.Freelancers'),
        ),
        migrations.AddField(
            model_name='participatein',
            name='fid',
            field=models.ForeignKey(db_column='Fid', on_delete=django.db.models.deletion.CASCADE, to='headhunt.Freelancers'),
        ),
        migrations.AddField(
            model_name='message',
            name='cid',
            field=models.ForeignKey(db_column='Cid', on_delete=django.db.models.deletion.CASCADE, to='headhunt.Clients'),
        ),
        migrations.AddField(
            model_name='fproficiency',
            name='fid',
            field=models.ForeignKey(blank=True, db_column='Fid', null=True, on_delete=django.db.models.deletion.CASCADE, to='headhunt.Freelancers'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='cid',
            field=models.ForeignKey(db_column='Cid', on_delete=django.db.models.deletion.CASCADE, to='headhunt.Clients'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='fid',
            field=models.ForeignKey(db_column='Fid', on_delete=django.db.models.deletion.CASCADE, to='headhunt.Freelancers'),
        ),
        migrations.AlterUniqueTogether(
            name='tcontracts',
            unique_together=set([('cid', 'tname', 'rid')]),
        ),
        migrations.AlterUniqueTogether(
            name='requestask',
            unique_together=set([('rid', 'fid')]),
        ),
        migrations.AlterUniqueTogether(
            name='participatein',
            unique_together=set([('tname', 'fid')]),
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together=set([('rid', 'cid')]),
        ),
        migrations.AlterUniqueTogether(
            name='contracts',
            unique_together=set([('cid', 'fid', 'rid')]),
        ),
    ]
