# Generated by Django 2.1.3 on 2018-12-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headhunt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_admin',
            field=models.BooleanField(blank=True, db_column='Is_admin', default=False, null=True),
        ),
    ]
