# Generated by Django 2.1.3 on 2018-12-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headhunt', '0002_auto_20181204_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_admin',
            field=models.BooleanField(blank=True, db_column='Is_admin', default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='pw',
            field=models.CharField(db_column='Pw', max_length=50),
        ),
    ]
